server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: test_usr
    password: test_usr
    tomcat:
      max-wait: 20000
      max-active: 20
      max-idle: 50
      min-idle: 15
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id.new_generator_mappings: false
        format_sql: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE