server:
  port: 8085
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useSSL=false
    username: test
    password: test
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 25
      min-idle: 15
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id.new_generator_mappings: false
        format_sql: true
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/fragments/
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
management:
  security:
    enabled: false